BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Jogadores" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"NOME"	TEXT NOT NULL UNIQUE,
	"DATA_REGISTRO"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Partidas" (
	"ID"	INTEGER UNIQUE,
	"ID_JOGADORES"	INTEGER NOT NULL,
	"DATA_INICIO"	TEXT NOT NULL,
	"DATA_FINALIZAÇÃO"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
